### ISSUE TITLE
Unable to save page without URL, when Title provided

### ISSUE THREAD

**Issue by mihy** [TypiCMS/Pages#13]
I can not save page (homepage) with title, but without URL. There is 
`'slug.*' => 'nullable|alpha_dash|max:255|required_with:title.*',`
but when 'Is home'is provided as `true`, maybe this is wrong validation rule?

**Comment by sdebacker** [comment]
If the page is set as homepage, it will be accessible without slug even if there is a slug. But it should be improved, PR welcome.

**Comment by deveti** [comment]
@sdebacker I came across the same issue and I found a simple fix. Pull request is prepared. Thank you.

**Comment by deveti** [comment]
@sdebacker also, if page is marked as home page (and has a slug) and is included in menu, generated url will include /slug. While homepage will load without a slug, page navigation will not be consistent.

**Comment by sdebacker** [comment]
Fixed, thank you.
